### PR TITLE
Update to 1.8.8

### PR DESCRIPTION
**Pull request by jokva**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jokva** [comment]
@conda-forge-admin, please rerender

**Comment by jokva** [comment]
@conda-forge-admin, please rerender

**Comment by jokva** [comment]
I don't know why this fails on Windows, or if it supposed to, but I _think_ I saw the same thing when I submitted the original package, and it had to do with it being attempted from a fork where the env is not completely available.

**Comment by chrisburr** [comment]
It's not very clear but the log contains `D:\bld\segyio_1569309557906\_h_env\python.exe: can't open file 'setup.py': [Errno 2] No such file or directory`.

Where is that file supposed to come from? Is there a reason why the `bld.bat` (Windows) uses `-DBUILD_PYTHON=OFF` and `%PYTHON% setup.py build_ext -L %PREFIX%\lib install --prefix %PREFIX%` but the `build.sh` (macOS/Linux) doesn't?

**Comment by jokva** [comment]
You're right (and it's not clear at all), but the file has indeed moved, and it looks like the job wasn't updated. My apologies.

I'll push a fix right away.

**Comment by jokva** [comment]
> Where is that file supposed to come from?
It used to be in the project root, but was moved in a build system refactor.

> Is there a reason why the bld.bat (Windows) uses -DBUILD_PYTHON=OFF and %PYTHON% setup.py build_ext -L %PREFIX%\lib install --prefix %PREFIX% but the build.sh (macOS/Linux) doesn't?

I cannot recall, to be quite honest, but I remember struggling with the conda build environment if cmake did it all. Once this is figured out I'd be happy to try just doing everything from cmake again.

**Pull request merged**
