### PR TITLE
Update version to 1.9.3

### PR DESCRIPTION
**Pull request by Anthchirp**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
failing with
```
2020-10-12T16:23:25.3379001Z [ 33%] Built target segyio-python
2020-10-12T16:23:25.3467961Z Scanning dependencies of target apputils
2020-10-12T16:23:25.3545987Z [ 37%] Building C object applications/CMakeFiles/apputils.dir/apputils.c.o
2020-10-12T16:23:25.3808761Z /home/conda/feedstock_root/build_artifacts/segyio_1602519552686/work/applications/apputils.c: In function 'printversion':
2020-10-12T16:23:25.3809874Z <command-line>:0:14: error: 'v1' undeclared (first use in this function)
2020-10-12T16:23:25.3811068Z /home/conda/feedstock_root/build_artifacts/segyio_1602519552686/work/applications/apputils.c:55:50: note: in expansion of macro 'segyio_MAJOR'
2020-10-12T16:23:25.3811740Z      printf( "%s (segyio version %d.%d)\n", name, segyio_MAJOR, segyio_MINOR );
2020-10-12T16:23:25.3812201Z                                                   ^~~~~~~~~~~~
2020-10-12T16:23:25.3813164Z <command-line>:0:14: note: each undeclared identifier is reported only once for each function it appears in
2020-10-12T16:23:25.3814301Z /home/conda/feedstock_root/build_artifacts/segyio_1602519552686/work/applications/apputils.c:55:50: note: in expansion of macro 'segyio_MAJOR'
2020-10-12T16:23:25.3815551Z      printf( "%s (segyio version %d.%d)\n", name, segyio_MAJOR, segyio_MINOR );
2020-10-12T16:23:25.3815993Z                                                   ^~~~~~~~~~~~
2020-10-12T16:23:25.3836107Z gmake[2]: *** [applications/CMakeFiles/apputils.dir/apputils.c.o] Error 1
```

**Comment by jokva** [comment]
Yes, the tag parsing logic assumes no leading v, but it was tagged _with_ a leading v. I've published a new tag.

**Comment by jokva** [comment]
With the availability of the 1.9.3 tag, the makefile patch shouldn't be necessary. I'll close this so we can make a new 1.9.3 build PR without patches.

**Comment by Anthchirp** [comment]
I could just have taken the commit off 🤷‍♂️

**Pull request closed without merging**
